"""initial schema

Revision ID: 30d8a25ac98c
Revises:
Create Date: 2026-07-14 00:20:25.761048
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30d8a25ac98c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_config", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saved_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("cron", sa.String(), nullable=False),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.String(), nullable=True),
        sa.Column("next_run_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("finished_at", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("progress_stage", sa.String(), nullable=True),
        sa.Column("composite_score", sa.Integer(), nullable=True),
        sa.Column("report_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index("ix_run_account", ["account_id", "created_at"], unique=False)

    op.create_table(
        "finding_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("check_id", sa.String(), nullable=False),
        sa.Column("principal_uid", sa.String(), nullable=True),
        sa.Column("first_seen_run", sa.Integer(), nullable=True),
        sa.Column("last_seen_run", sa.Integer(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("ticket_ref", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_run"],
            ["run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_run"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "fingerprint", name="uq_group_account_fingerprint"),
    )
    with op.batch_alter_table("finding_group", schema=None) as batch_op:
        batch_op.create_index("ix_group_fingerprint", ["fingerprint"], unique=False)

    op.create_table(
        "log_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.String(), nullable=True),
        sa.Column("principal_uid", sa.String(), nullable=True),
        sa.Column("source_ip", sa.String(), nullable=True),
        sa.Column("event_name", sa.String(), nullable=True),
        sa.Column("event_source", sa.String(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("is_privileged", sa.Boolean(), nullable=False),
        sa.Column("is_sensitive_iam", sa.Boolean(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("log_event", schema=None) as batch_op:
        batch_op.create_index("ix_log_run_principal", ["run_id", "principal_uid"], unique=False)

    op.create_table(
        "permission_edge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("src_type", sa.String(), nullable=False),
        sa.Column("src_uid", sa.String(), nullable=False),
        sa.Column("dst_type", sa.String(), nullable=False),
        sa.Column("dst_uid", sa.String(), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("effect", sa.String(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permission_edge", schema=None) as batch_op:
        batch_op.create_index("ix_edge_run_src", ["run_id", "src_uid"], unique=False)

    op.create_table(
        "policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("policy_uid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=True),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("statement_count", sa.Integer(), nullable=True),
        sa.Column("has_wildcard_action", sa.Boolean(), nullable=True),
        sa.Column("has_wildcard_resource", sa.Boolean(), nullable=True),
        sa.Column("uses_not_action", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.create_index("ix_policy_run", ["run_id"], unique=False)

    op.create_table(
        "principal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("principal_uid", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("arn", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("account_type", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("console_access", sa.Boolean(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.String(), nullable=True),
        sa.Column("password_last_changed", sa.String(), nullable=True),
        sa.Column("access_key_age_days", sa.Integer(), nullable=True),
        sa.Column("attached_policy_ids", sa.JSON(), nullable=True),
        sa.Column("blast_radius_score", sa.Integer(), nullable=True),
        sa.Column("reachable_actions", sa.Integer(), nullable=True),
        sa.Column("reachable_sensitive", sa.Integer(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("principal", schema=None) as batch_op:
        batch_op.create_index("ix_principal_run", ["run_id"], unique=False)
        batch_op.create_index("ix_principal_uid", ["principal_uid"], unique=False)

    op.create_table(
        "run_summary",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("total_findings", sa.Integer(), nullable=False),
        sa.Column("count_low", sa.Integer(), nullable=False),
        sa.Column("count_medium", sa.Integer(), nullable=False),
        sa.Column("count_high", sa.Integer(), nullable=False),
        sa.Column("count_critical", sa.Integer(), nullable=False),
        sa.Column("counts_by_category", sa.JSON(), nullable=False),
        sa.Column("counts_by_status", sa.JSON(), nullable=False),
        sa.Column("compliance_summary", sa.JSON(), nullable=False),
        sa.Column("new_count", sa.Integer(), nullable=True),
        sa.Column("resolved_count", sa.Integer(), nullable=True),
        sa.Column("principals_total", sa.Integer(), nullable=True),
        sa.Column("principals_at_risk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("principal_uid", sa.String(), nullable=True),
        sa.Column("resource", sa.String(), nullable=True),
        sa.Column("policy_uid", sa.String(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("likelihood", sa.Integer(), nullable=True),
        sa.Column("impact", sa.Integer(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("remediation_snippet", sa.Text(), nullable=True),
        sa.Column("compliance_tags", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["finding_group.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.create_index("ix_finding_group", ["group_id"], unique=False)
        batch_op.create_index("ix_finding_run", ["run_id", "severity"], unique=False)

    op.create_table(
        "finding_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("edited_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["finding_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finding_exception",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.Column("revoked_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["finding_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finding_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(), nullable=True),
        sa.Column("to_status", sa.String(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["finding_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_status_history")
    op.drop_table("finding_exception")
    op.drop_table("finding_comment")
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.drop_index("ix_finding_run")
        batch_op.drop_index("ix_finding_group")

    op.drop_table("finding")
    op.drop_table("run_summary")
    with op.batch_alter_table("principal", schema=None) as batch_op:
        batch_op.drop_index("ix_principal_uid")
        batch_op.drop_index("ix_principal_run")

    op.drop_table("principal")
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.drop_index("ix_policy_run")

    op.drop_table("policy")
    with op.batch_alter_table("permission_edge", schema=None) as batch_op:
        batch_op.drop_index("ix_edge_run_src")

    op.drop_table("permission_edge")
    with op.batch_alter_table("log_event", schema=None) as batch_op:
        batch_op.drop_index("ix_log_run_principal")

    op.drop_table("log_event")
    with op.batch_alter_table("finding_group", schema=None) as batch_op:
        batch_op.drop_index("ix_group_fingerprint")

    op.drop_table("finding_group")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index("ix_run_account")

    op.drop_table("run")
    op.drop_table("schedule")
    op.drop_table("saved_view")
    op.drop_table("audit_event")
    op.drop_table("account")
    op.drop_table("app_user")
    # ### end Alembic commands ###
